### ISSUE TITLE
Invalid error message alignment

### ISSUE THREAD

**Issue by koral--** [bitrise-io/steps-git-clone#63] opened 2017-12-18 19:44 UTC
![image](https://user-images.githubusercontent.com/3340954/34124291-999829c2-e432-11e7-9a08-a14b1e5cc724.png)
The last warning is red, while fatal error is white.

It seems that first line of the output from 3rd attempt is printed red as an overall result and the next line is not coloured.
Maybe all the overall error message should be red?

Screenshot contents is produced by version 3.5.1 of the step however, I haven't found anything related in release notes at: https://github.com/bitrise-io/steps-git-clone/releases

**Comment by viktorbenei** [comment] 2017-12-18 19:59
v4 includes tons of changes (was pretty much a complete rewrite), so could you please try it again with the latest version of the step @koral-- ?

**Comment by koral--** [comment] 2017-12-20 02:42
Here is how it looks like on 4.0.4 (error I simulated is a little bit different but it doesn't matter):
![image](https://user-images.githubusercontent.com/3340954/34188491-fb7421dc-e536-11e7-8f56-a9045fef8074.png)

Coloring seems to be fine but yellow text is not properly aligned vertically. Highlighted text appears 2 times in area of `Attempt 2` but not once in `Attempt 1`.

**Comment by viktorbenei** [comment] 2017-12-21 14:35
@koral-- thanks for the report & screen shot!

Re:

> Coloring seems to be fine but yellow text is not properly aligned vertically. Highlighted text appears 2 times in area of Attempt 2 but not once in Attempt 1.

That's not the fault of the step directly, it affects Bitrise logs sometimes if stdout and stderr are both written at about the same time on Linux.

We're still searching for exactly what might cause this, and we only saw this happening on Linux; most likely some kind of stderr buffering delay is the root cause as technically we just use Go's built in "Combined Output" method, which returns both the stdout and stderr in the same string/buffer. 

That issue is tracked at https://github.com/bitrise-io/bitrise/issues/546 (was also reported by you ;) ), so I'll close this issue here, but feel free to comment if we missed anything and we'll reopen it :)

**Closed by viktorbenei** 2017-12-21 14:35 UTC
