### ISSUE TITLE
Failed, error: fatal: no submodule mapping found in .gitmodules for path 'react-components'

### ISSUE THREAD

**Issue by shahidjabbar** [bitrise-io/steps-git-clone#34] opened 2017-06-12 13:49 UTC
I am getting this error while adding a new react native repository to bitrise. 
```
Failed, error: fatal: no submodule mapping found in .gitmodules for path 'react-components'

|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Git Clone Repository (exit code: 1)                           | 9.16 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-git-clone/issues          |
| Source: https://github.com/bitrise-io/steps-git-clone                        |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment] 2017-06-12 14:10
Duplicate of https://discuss.bitrise.io/t/failed-error-no-submodule-mapping-found-in-gitmodules-for-path-src-github-com-mattermost-platform/1502/2

If you have any question please leave a comment there!

**Closed by viktorbenei** 2017-06-12 14:10 UTC

**Comment by shahidjabbar** [comment] 2017-06-12 14:13
Sorry for that. The problem was in a deleted but not git removed submodules.

**Comment by viktorbenei** [comment] 2017-06-12 14:14
No problem at all @shahidjabbar , I'm glad to hear you managed to solve the issue :)
