### ISSUE TITLE
Regression: Change of PR branch merge strategy in 4.0.6 breaks some repositories

### ISSUE THREAD

**Issue by akashivskyy** [bitrise-io/steps-git-clone#70] opened 2018-01-31 17:09 UTC
Change introduced  in #68 and released in 4.0.6 breaks some repositories using PR triggers.

Here's an example log:

```none
- CloneIntoDir: /Users/vagrant/git
- RepositoryURL: git@github.com:[redacted]/[redacted].git
- UpdateSubmodules: true
Git Checkout config:
- Commit: [redacted]
- Tag: 
- Branch: [redacted]
- CloneDepth: 1
Git Pull Request config:
- PRRepositoryCloneURL: git@github.com:[redacted]/[redacted].git
- PRID: 794
- BranchDest: develop
- PRMergeBranch: pull/794/merge
- ResetRepository: false
- ManualMerge: false
Bitrise Build config:
- BuildURL: https://www.bitrise.io/build/[redacted]
- BuildAPIToken: [redacted]
git "init"
Initialized empty Git repository in /Users/vagrant/git/.git/
git "remote" "add" "origin" "git@github.com:[redacted]/[redacted].git"
git "fetch" "--depth=1"
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
From github.com:[redacted]/[redacted]
 * [new branch]      develop      -> origin/develop
 * [new branch]      master       -> origin/master
 * [new branch]      [redacted] -> origin/[redacted]
 * [new branch]      [redacted] -> origin/[redacted]
 * [new branch]      [redacted] -> origin/[redacted]
git "fetch" "origin" "pull/794/head:pull/794"
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
From github.com:[redacted]/[redacted]
 * [new ref]         refs/pull/794/head -> pull/794
git "checkout" "develop"
Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
git "merge" "origin/develop"
Already up to date.
git "merge" "pull/794"
fatal: refusing to merge unrelated histories
ERROR: auto merge, error: merge "pull/794": exit status 128
```

**Comment by viktorbenei** [comment] 2018-01-31 17:16
Thanks for reporting @akashivskyy and sorry for the inconvenience!

We'll fix this ASAP, just a note: the issue is caused by the `depth:1` param; if you remove the depth limit it'll work as expected. Reverting to the previous version of course also works, and we're already working on the fix!

**Comment by viktorbenei** [comment] 2018-01-31 18:02
Fixed in https://github.com/bitrise-io/steps-git-clone/releases/tag/4.0.7 (https://github.com/bitrise-io/steps-git-clone/pull/71), step update was also just published into the StepLib, should be available on the web UI soon as well.

Thanks again for reporting the issue @akashivskyy ! :)

**Closed by viktorbenei** 2018-01-31 18:02 UTC
Labels: bug
